stages:
  - test
  - dist

Dist:
  stage: dist
  script:
    - make dist
  tags:
    - linux
  only:
    - master

Test:
  stage: test
  script:
    - make test
  tags:
    - linux
  except:
    - tags
