---
apiVersion: v1
kind: Service
metadata:
  name: eve-sch-v1
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: api
    - port: 3001
      targetPort: 3001
      name: metrics
  selector:
    app: eve-sch-v1